// This file was autogenerated by cloop - Cross Language Object Oriented Programming



class IDisposable():
	
	VERSION = 1

	def dispose(self):


class IStatus(IDisposable):
	
	VERSION = 2

	ERROR_1 = int(1)
	ERROR_2 = int(0x2)
	ERROR_12 = int(IStatus_ERROR_1 | IStatus_ERROR_2)

	def dispose(self):

	def getCode(self):

	def setCode(self, code):


class IStatusFactory(IDisposable):
	
	VERSION = 2

	def dispose(self):

	def createStatus(self):


class IFactory(IDisposable):
	
	VERSION = 2

	def dispose(self):

	def createStatus(self):

	def createCalculator(self, status):

	def createCalculator2(self, status):

	def createBrokenCalculator(self, status):

	def setStatusFactory(self, statusFactory):


class ICalculator(IDisposable):
	
	VERSION = 4

	def dispose(self):

	def sum(self, status, n1, n2):

	def getMemory(self):

	def setMemory(self, n):

	def sumAndStore(self, status, n1, n2):


class ICalculator2(ICalculator):
	
	VERSION = 6

	def dispose(self):

	def sum(self, status, n1, n2):

	def getMemory(self):

	def setMemory(self, n):

	def sumAndStore(self, status, n1, n2):

	def multiply(self, status, n1, n2):

	def copyMemory(self, calculator):

	def copyMemory2(self, address):

